# Actividad 4 
# Halle el factor de fricción f a partir de la solucion numérica de la ecuación de Colebrook-White para una rugosidad relativa de etha/D = 0.00005 y el número de Reynolds Re= 10e8

In [1]:
import numpy as np

In [7]:
# Inputs 
r = 0.00005
Re =10**8
x0 = 64/Re
tol = 1e-7
fx = lambda x,r,Re: 1/np.sqrt(x) + (2*np.log10((2.51/(Re*np.sqrt(x)))+(r/3.71)))
dfx = lambda x,r,Re: (-0.5 / (x*np.sqrt(x))) - ((2/np.log(10)) * ((2.52/(Re*np.sqrt(x))) / ((2.52/(Re*np.sqrt(x))) + (r/3.71))))

print(x0)

6.4e-07


In [8]:
# Procedimiento
tabla = []
tramo = abs(2*tol)
xi = x0

while (tramo >= tol):
    xn = (xi - (fx(xi,r,Re)/dfx(xi,r,Re)))
    k = dfx(xi,r,Re)
    g = fx(xi,r,Re)
    n = g/k
    tramo = abs(xn - xi)
    tabla.append([xi, xn, tramo])
    xi = abs(xn)
    print(xi, n, g, k, tramo)

1.911094850126107e-06 -1.2710948501261073e-06 1241.3035653495117 -976562500.608322 1.271094850126107e-06
5.685731146992111e-06 -3.7746362968660037e-06 714.3676081730603 -189254686.27697554 3.7746362968660037e-06
1.6806665698308843e-05 -1.1120934551316734e-05 410.13970406298904 -36879967.43173243 1.1120934551316732e-05
4.912253018091709e-05 -3.2315864482608245e-05 234.51112844222425 -7256842.179432752 3.2315864482608245e-05
0.00014080124276822037 -9.167871258730329e-05 133.1427346638732 -1452275.3527661592 9.167871258730328e-05
0.00039027799222827883 -0.00024947674946005846 74.66043579914152 -299268.112001334 0.00024947674946005846
0.0010218343297813553 -0.0006315563375530766 40.95637508582492 -64849.91543986035 0.0006315563375530766
0.002432362344534515 -0.0014105280147531597 21.591476826353354 -15307.371849776291 0.0014105280147531597
0.0049677457101287 -0.002535383365594185 10.56755555718619 -4168.030642068052 0.0025353833655941847
0.00809780105503291 -0.0031300553449042103 4.4698177

In [9]:
# Convierte la lista a un arreglo
tabla = np.array(tabla)
n = len(tabla)

In [10]:
#Output

print(['xi', 'xn', 'tramo'])
np.set_printoptions(precision=4)
print(tabla)
print('raiz en:', xi)
print('con error de: ', tramo)

['xi', 'xn', 'tramo']
[[6.4000e-07 1.9111e-06 1.2711e-06]
 [1.9111e-06 5.6857e-06 3.7746e-06]
 [5.6857e-06 1.6807e-05 1.1121e-05]
 [1.6807e-05 4.9123e-05 3.2316e-05]
 [4.9123e-05 1.4080e-04 9.1679e-05]
 [1.4080e-04 3.9028e-04 2.4948e-04]
 [3.9028e-04 1.0218e-03 6.3156e-04]
 [1.0218e-03 2.4324e-03 1.4105e-03]
 [2.4324e-03 4.9677e-03 2.5354e-03]
 [4.9677e-03 8.0978e-03 3.1301e-03]
 [8.0978e-03 1.0123e-02 2.0252e-03]
 [1.0123e-02 1.0559e-02 4.3631e-04]
 [1.0559e-02 1.0573e-02 1.3805e-05]
 [1.0573e-02 1.0573e-02 7.9418e-09]]
raiz en: 0.010573078548777445
con error de:  7.941825487176035e-09
