In [83]:
import pandas as pd
import numpy as np
import mat4py

In [95]:
columns = ['Upstream - 1x', 'Upstream - 1y', 'Upstream - 1z', 'Upstream - 2x', 'Upstream - 2y', 'Upstream - 2z', 'Upstream - 3x', 'Upstream - 3y',
        'Upstream - 3z', 'Upstream - 4x', 'Upstream - 4y', 'Upstream - 4z', 'Downstream - 1x', 'Downstream - 1y', 'Downstream - 1z', 'Downstream - 2x',
        'Downstream - 2y', 'Downstream - 2z', 'Downstream - 3x', 'Downstream - 3y', 'Downstream - 3z', 'Downstream - 4x', 'Downstream - 4y', 'Downstream - 4z']
db_001_1 = pd.read_table('RW001_3D.tsv', delimiter='\t', header=None, names=columns, skiprows=1)
db_001_1.shape

(22500, 24)

In [96]:
db_001_1.head()

Upstream - 1x  Upstream - 1y  Upstream - 1z  Upstream - 2x  Upstream - 2y  \
0        551.863       1462.394        371.427        804.268       1654.505   
1        551.867       1462.359        371.439        804.282       1654.481   
2        551.864       1462.316        371.415        804.301       1654.540   
3        551.881       1462.321        371.430        804.265       1654.495   
4        551.887       1462.326        371.448        804.293       1654.505   

   Upstream - 2z  Upstream - 3x  Upstream - 3y  Upstream - 3z  Upstream - 4x  \
0        150.217        805.646       1511.831        148.611        317.568   
1        150.218        805.654       1511.826        148.622        317.543   
2        150.265        805.645       1511.780        148.609        317.550   
3        150.252        805.662       1511.802        148.653        317.572   
4        150.275        805.690       1511.808        148.649        317.566   

   ...  Downstream - 1z  Downstream - 2x  Downstream - 2y  Downstream - 2z  \
0  ...          150.614         -332.879         1374.738          150.936   
1  ...          150.577         -332.901         1374.714          150.890   
2  ...          150.634         -332.929         1374.702          150.914   
3  ...          150.608         -332.880         1374.792          150.991   
4  ...          150.650         -332.891         1374.686          150.939   

   Downstream - 3x  Downstream - 3y  Downstream - 3z  Downstream - 4x  \
0           89.714         1368.960          150.132          -93.592   
1           89.721         1368.964          150.130          -93.613   
2           89.718         1368.954          150.140          -93.626   
3           89.706         1368.923          150.156          -93.594   
4           89.709         1368.902          150.133          -93.592   

   Downstream - 4y  Downstream - 4z  
0         1464.657          354.984  
1         1464.735          355.009  
2         1464.655          354.997  
3         1464.676          354.990  
4         1464.682          355.002  

[5 rows x 24 columns]

In [97]:
db_001_2 = pd.read_table('RW001_3D.tsv', delimiter='\t', header=None, skiprows=1)
db_001_2.head()

0         1        2        3         4        5        6         7   \
0  551.863  1462.394  371.427  804.268  1654.505  150.217  805.646  1511.831   
1  551.867  1462.359  371.439  804.282  1654.481  150.218  805.654  1511.826   
2  551.864  1462.316  371.415  804.301  1654.540  150.265  805.645  1511.780   
3  551.881  1462.321  371.430  804.265  1654.495  150.252  805.662  1511.802   
4  551.887  1462.326  371.448  804.293  1654.505  150.275  805.690  1511.808   

        8        9   ...       14       15        16       17      18  \
0  148.611  317.568  ...  150.614 -332.879  1374.738  150.936  89.714   
1  148.622  317.543  ...  150.577 -332.901  1374.714  150.890  89.721   
2  148.609  317.550  ...  150.634 -332.929  1374.702  150.914  89.718   
3  148.653  317.572  ...  150.608 -332.880  1374.792  150.991  89.706   
4  148.649  317.566  ...  150.650 -332.891  1374.686  150.939  89.709   

         19       20      21        22       23  
0  1368.960  150.132 -93.592  1464.657  354.984  
1  1368.964  150.130 -93.613  1464.735  355.009  
2  1368.954  150.140 -93.626  1464.655  354.997  
3  1368.923  150.156 -93.594  1464.676  354.990  
4  1368.902  150.133 -93.592  1464.682  355.002  

[5 rows x 24 columns]

In [98]:
df = db_001_2.to_numpy()
df

array([[ 551.863, 1462.394,  371.427, ...,  -93.592, 1464.657,  354.984],
       [ 551.867, 1462.359,  371.439, ...,  -93.613, 1464.735,  355.009],
       [ 551.864, 1462.316,  371.415, ...,  -93.626, 1464.655,  354.997],
       ...,
       [ 551.693, 1462.551,  370.591, ...,  -93.561, 1464.759,  355.154],
       [ 551.701, 1462.534,  370.611, ...,  -93.556, 1464.792,  355.189],
       [ 551.693, 1462.568,  370.629, ...,  -93.55 , 1464.807,  355.195]])

In [101]:
df.shape

(22500, 24)

In [115]:
import numpy as np

arr = np.reshape(df, (df.shape[0], 8, 3))
u1 = arr[:,0,:]
u2 = arr[:,1,:]
u3 = arr[:,2,:]
u4 = arr[:,3,:]
d1 = arr[:,4,:]
d2 = arr[:,5,:]
d3 = arr[:,6,:]
d4 = arr[:,7,:]

arr = np.array([u1,u2,u3,u4,d1,d2,d3,d4])
arr

array([[[ 551.863, 1462.394,  371.427],
        [ 551.867, 1462.359,  371.439],
        [ 551.864, 1462.316,  371.415],
        ...,
        [ 551.693, 1462.551,  370.591],
        [ 551.701, 1462.534,  370.611],
        [ 551.693, 1462.568,  370.629]],

       [[ 804.268, 1654.505,  150.217],
        [ 804.282, 1654.481,  150.218],
        [ 804.301, 1654.54 ,  150.265],
        ...,
        [ 803.85 , 1654.248,  148.786],
        [ 803.853, 1654.227,  148.828],
        [ 803.837, 1654.219,  148.809]],

       [[ 805.646, 1511.831,  148.611],
        [ 805.654, 1511.826,  148.622],
        [ 805.645, 1511.78 ,  148.609],
        ...,
        [ 805.211, 1511.48 ,  147.422],
        [ 805.22 , 1511.511,  147.458],
        [ 805.18 , 1511.529,  147.49 ]],

       ...,

       [[-332.879, 1374.738,  150.936],
        [-332.901, 1374.714,  150.89 ],
        [-332.929, 1374.702,  150.914],
        ...,
        [-333.204, 1374.314,  151.699],
        [-333.218, 1374.298,  151.764],
        [

In [119]:
iterables=[['Upstream - 1', 'Upstream - 2', 'Upstream - 3', 'Upstream - 4',
       'Downstream - 1', 'Downstream - 2', 'Downstream - 3', 'Downstream - 4'], ['X','Y','Z']]

index = pd.MultiIndex.from_product(iterables, names=['first', 'second'])

db_001_3 = pd.read_table('RW001_3D.tsv',delimiter='\t', header=0, names=index)
db_001_3.head()

Upstream - 1                    Upstream - 2                     \
             X         Y        Z            X         Y        Z   
0      551.863  1462.394  371.427      804.268  1654.505  150.217   
1      551.867  1462.359  371.439      804.282  1654.481  150.218   
2      551.864  1462.316  371.415      804.301  1654.540  150.265   
3      551.881  1462.321  371.430      804.265  1654.495  150.252   
4      551.887  1462.326  371.448      804.293  1654.505  150.275   

  Upstream - 3                    Upstream - 4  ... Downstream - 1  \
             X         Y        Z            X  ...              Z   
0      805.646  1511.831  148.611      317.568  ...        150.614   
1      805.654  1511.826  148.622      317.543  ...        150.577   
2      805.645  1511.780  148.609      317.550  ...        150.634   
3      805.662  1511.802  148.653      317.572  ...        150.608   
4      805.690  1511.808  148.649      317.566  ...        150.650   

  Downstream - 2                    Downstream - 3                     \
               X         Y        Z              X         Y        Z   
0       -332.879  1374.738  150.936         89.714  1368.960  150.132   
1       -332.901  1374.714  150.890         89.721  1368.964  150.130   
2       -332.929  1374.702  150.914         89.718  1368.954  150.140   
3       -332.880  1374.792  150.991         89.706  1368.923  150.156   
4       -332.891  1374.686  150.939         89.709  1368.902  150.133   

  Downstream - 4                     
               X         Y        Z  
0        -93.592  1464.657  354.984  
1        -93.613  1464.735  355.009  
2        -93.626  1464.655  354.997  
3        -93.594  1464.676  354.990  
4        -93.592  1464.682  355.002  

[5 rows x 24 columns]

In [93]:
db_001.columns

Index(['Upstream - 1', 'Upstream - 2', 'Upstream - 3', 'Upstream - 4',
       'Downstream - 1', 'Downstream - 2', 'Downstream - 3', 'Downstream - 4'],
      dtype='object')

In [86]:
db_001 = pd.read_table('RW001_3D.tsv',delimiter='\t')
db_001.head()

Upstream - 1  \
551.863 1462.394 371.427 804.268 1654.505 150.217 805.646 1511.831 148.611 317.568 1660.961 152.121 -334.532 1519.177 150.614 -332.879      1374.738   
551.867 1462.359 371.439 804.282 1654.481 150.218 805.654 1511.826 148.622 317.543 1661.033 152.193 -334.531 1519.108 150.577 -332.901      1374.714   
551.864 1462.316 371.415 804.301 1654.540 150.265 805.645 1511.780 148.609 317.550 1661.027 152.199 -334.524 1519.144 150.634 -332.929      1374.702   
551.881 1462.321 371.430 804.265 1654.495 150.252 805.662 1511.802 148.653 317.572 1661.040 152.205 -334.530 1519.144 150.608 -332.880      1374.792   
551.887 1462.326 371.448 804.293 1654.505 150.275 805.690 1511.808 148.649 317.566 1661.033 152.256 -334.520 1519.116 150.650 -332.891      1374.686   

                                                                                                                                        Upstream - 2  \
551.863 1462.394 371.427 804.268 1654.505 150.217 805.646 1511.831 148.611 317.568 1660.961 152.121 -334.532 1519.177 150.614 -332.879       150.936   
551.867 1462.359 371.439 804.282 1654.481 150.218 805.654 1511.826 148.622 317.543 1661.033 152.193 -334.531 1519.108 150.577 -332.901       150.890   
551.864 1462.316 371.415 804.301 1654.540 150.265 805.645 1511.780 148.609 317.550 1661.027 152.199 -334.524 1519.144 150.634 -332.929       150.914   
551.881 1462.321 371.430 804.265 1654.495 150.252 805.662 1511.802 148.653 317.572 1661.040 152.205 -334.530 1519.144 150.608 -332.880       150.991   
551.887 1462.326 371.448 804.293 1654.505 150.275 805.690 1511.808 148.649 317.566 1661.033 152.256 -334.520 1519.116 150.650 -332.891       150.939   

                                                                                                                                        Upstream - 3  \
551.863 1462.394 371.427 804.268 1654.505 150.217 805.646 1511.831 148.611 317.568 1660.961 152.121 -334.532 1519.177 150.614 -332.879        89.714   
551.867 1462.359 371.439 804.282 1654.481 150.218 805.654 1511.826 148.622 317.543 1661.033 152.193 -334.531 1519.108 150.577 -332.901        89.721   
551.864 1462.316 371.415 804.301 1654.540 150.265 805.645 1511.780 148.609 317.550 1661.027 152.199 -334.524 1519.144 150.634 -332.929        89.718   
551.881 1462.321 371.430 804.265 1654.495 150.252 805.662 1511.802 148.653 317.572 1661.040 152.205 -334.530 1519.144 150.608 -332.880        89.706   
551.887 1462.326 371.448 804.293 1654.505 150.275 805.690 1511.808 148.649 317.566 1661.033 152.256 -334.520 1519.116 150.650 -332.891        89.709   

                                                                                                                                        Upstream - 4  \
551.863 1462.394 371.427 804.268 1654.505 150.217 805.646 1511.831 148.611 317.568 1660.961 152.121 -334.532 1519.177 150.614 -332.879      1368.960   
551.867 1462.359 371.439 804.282 1654.481 150.218 805.654 1511.826 148.622 317.543 1661.033 152.193 -334.531 1519.108 150.577 -332.901      1368.964   
551.864 1462.316 371.415 804.301 1654.540 150.265 805.645 1511.780 148.609 317.550 1661.027 152.199 -334.524 1519.144 150.634 -332.929      1368.954   
551.881 1462.321 371.430 804.265 1654.495 150.252 805.662 1511.802 148.653 317.572 1661.040 152.205 -334.530 1519.144 150.608 -332.880      1368.923   
551.887 1462.326 371.448 804.293 1654.505 150.275 805.690 1511.808 148.649 317.566 1661.033 152.256 -334.520 1519.116 150.650 -332.891      1368.902   

                                                                                                                                        Downstream - 1  \
551.863 1462.394 371.427 804.268 1654.505 150.217 805.646 1511.831 148.611 317.568 1660.961 152.121 -334.532 1519.177 150.614 -332.879         150.132   
551.867 1462.359 371.439 804.282 1654.481 150.218 805.654 1511.826 148.622 317.543 1661.033 152.193 -334.531 1519.108 150.577 -332.901         150.130   
551.864 1462.316 371.4

In [89]:
db_001.shape

(22500, 8)

In [87]:
db_001['Upstream - 1'].head()

551.863  1462.394  371.427  804.268  1654.505  150.217  805.646  1511.831  148.611  317.568  1660.961  152.121  -334.532  1519.177  150.614  -332.879    1374.738
551.867  1462.359  371.439  804.282  1654.481  150.218  805.654  1511.826  148.622  317.543  1661.033  152.193  -334.531  1519.108  150.577  -332.901    1374.714
551.864  1462.316  371.415  804.301  1654.540  150.265  805.645  1511.780  148.609  317.550  1661.027  152.199  -334.524  1519.144  150.634  -332.929    1374.702
551.881  1462.321  371.430  804.265  1654.495  150.252  805.662  1511.802  148.653  317.572  1661.040  152.205  -334.530  1519.144  150.608  -332.880    1374.792
551.887  1462.326  371.448  804.293  1654.505  150.275  805.690  1511.808  148.649  317.566  1661.033  152.256  -334.520  1519.116  150.650  -332.891    1374.686
Name: Upstream - 1, dtype: float64

In [90]:
db_001['Upstream - 2'].head()

551.863  1462.394  371.427  804.268  1654.505  150.217  805.646  1511.831  148.611  317.568  1660.961  152.121  -334.532  1519.177  150.614  -332.879    150.936
551.867  1462.359  371.439  804.282  1654.481  150.218  805.654  1511.826  148.622  317.543  1661.033  152.193  -334.531  1519.108  150.577  -332.901    150.890
551.864  1462.316  371.415  804.301  1654.540  150.265  805.645  1511.780  148.609  317.550  1661.027  152.199  -334.524  1519.144  150.634  -332.929    150.914
551.881  1462.321  371.430  804.265  1654.495  150.252  805.662  1511.802  148.653  317.572  1661.040  152.205  -334.530  1519.144  150.608  -332.880    150.991
551.887  1462.326  371.448  804.293  1654.505  150.275  805.690  1511.808  148.649  317.566  1661.033  152.256  -334.520  1519.116  150.650  -332.891    150.939
Name: Upstream - 2, dtype: float64

In [88]:
db_001['Upstream - 1'].values[0:3]

array([1374.738, 1374.714, 1374.702])