In [2]:
# Importando librerias 
import numpy as np
import math
from UQpy.distributions import Uniform, JointIndependent, Normal
from UQpy.surrogates import *
from UQpy.sensitivity import *

In [3]:
# function to be approximated
def Margen(x):
    """QoI"""
    term1 = (x[0]*(x[1]**2))/2
    term2 = 3.81/(x[3]*x[5])
    term3 = 1.13/(x[2]*x[4])
    return 0.03 - term1*(term2+term3)

In [4]:
# datos de varianza
vm_q = 2*(10**4)
vm_l = 12
vm_As = 9.82*(10**-4)
vm_Ac = 0.04
vm_Es = 2*(10**11)
vm_Ec = 3*(10**10)

de_q = 0.07*vm_q
de_l = 0.01*vm_l
de_As = 0.06*vm_As
de_Ac = 0.12*vm_Ac
de_Es = 0.06*vm_Es
de_Ec = 0.06*vm_Ec

# input distributions
q = Normal(loc= vm_q, scale= de_q)
l = Normal(loc= vm_l, scale= de_l)
As = Normal(loc= vm_As, scale= de_As)
Ac = Normal(loc= vm_Ac, scale= de_Ac)
Es = Normal(loc= vm_Es, scale= de_Es)
Ec = Normal(loc= vm_Ec, scale= de_Ec)

marg = [q,l,As,Ac,Es,Ec]
joint = JointIndependent(marginals=marg)

In [9]:
# maximum polynomial degree
P = 1
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)


Polynomial degree: 1
Size of PCE basis: 7
Size of experimental design: 35
PCE mean estimate: 0.017034729302741518
PCE variance estimate: 1.779252507581926e-06
First-order Sobol indices:
[[0.41669965]
 [0.04718259]
 [0.14563758]
 [0.18498593]
 [0.14874785]
 [0.0567464 ]]
Total-order Sobol indices:
[[0.41669965]
 [0.04718259]
 [0.14563758]
 [0.18498593]
 [0.14874785]
 [0.0567464 ]]


In [10]:
# maximum polynomial degree
P = 2
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)

Polynomial degree: 2
Size of PCE basis: 28
Size of experimental design: 140
PCE mean estimate: 0.016994887384573772
PCE variance estimate: 1.8340344989729454e-06
First-order Sobol indices:
[[0.44703543]
 [0.03761485]
 [0.13989304]
 [0.18792959]
 [0.13891389]
 [0.04419493]]
Total-order Sobol indices:
[[0.44952529]
 [0.03808208]
 [0.14104033]
 [0.18998198]
 [0.14031551]
 [0.04547308]]


In [11]:
# maximum polynomial degree
P = 3
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)

Polynomial degree: 3
Size of PCE basis: 84
Size of experimental design: 420
PCE mean estimate: 0.01699546781290035
PCE variance estimate: 1.838933359704997e-06
First-order Sobol indices:
[[0.45000113]
 [0.03672228]
 [0.13947313]
 [0.18715893]
 [0.1393665 ]
 [0.04334059]]
Total-order Sobol indices:
[[0.45257046]
 [0.03710362]
 [0.14070318]
 [0.18872442]
 [0.14060722]
 [0.04423881]]


In [12]:
# maximum polynomial degree
P = 4
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)

Polynomial degree: 4
Size of PCE basis: 210
Size of experimental design: 1050
PCE mean estimate: 0.016995359476154586
PCE variance estimate: 1.8389987880766238e-06
First-order Sobol indices:
[[0.45052344]
 [0.03677044]
 [0.13941709]
 [0.18644095]
 [0.13936899]
 [0.04340063]]
Total-order Sobol indices:
[[0.45320791]
 [0.037156  ]
 [0.14067232]
 [0.18811177]
 [0.14062468]
 [0.04431353]]


In [13]:
# maximum polynomial degree
P = 5
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)

Polynomial degree: 5
Size of PCE basis: 462
Size of experimental design: 2310
PCE mean estimate: 0.01699530905602357
PCE variance estimate: 1.839934649609088e-06
First-order Sobol indices:
[[0.45042647]
 [0.03676577]
 [0.13928756]
 [0.18667886]
 [0.13934415]
 [0.0434096 ]]
Total-order Sobol indices:
[[0.45311099]
 [0.03715167]
 [0.14054092]
 [0.18836426]
 [0.14059795]
 [0.04432926]]


In [14]:
# maximum polynomial degree
P = 6
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)

Polynomial degree: 6
Size of PCE basis: 924
Size of experimental design: 4620
PCE mean estimate: 0.016995347965033523
PCE variance estimate: 1.839729617026796e-06
First-order Sobol indices:
[[0.45043872]
 [0.0367662 ]
 [0.13935118]
 [0.18659852]
 [0.13935402]
 [0.0434081 ]]
Total-order Sobol indices:
[[0.45311853]
 [0.03715131]
 [0.14060576]
 [0.18827807]
 [0.14060841]
 [0.04432851]]


In [15]:
# maximum polynomial degree
P = 7
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)

Polynomial degree: 7
Size of PCE basis: 1716
Size of experimental design: 8580
PCE mean estimate: 0.016995348178102207
PCE variance estimate: 1.8397322099382048e-06
First-order Sobol indices:
[[0.45044351]
 [0.03676514]
 [0.13935103]
 [0.18659819]
 [0.13935175]
 [0.0434072 ]]
Total-order Sobol indices:
[[0.45312326]
 [0.0371502 ]
 [0.1406054 ]
 [0.18827787]
 [0.14060614]
 [0.04432767]]


In [16]:
# maximum polynomial degree
P = 8
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)

Polynomial degree: 8
Size of PCE basis: 3003
Size of experimental design: 15015
PCE mean estimate: 0.01699534793743059
PCE variance estimate: 1.8397368569607541e-06
First-order Sobol indices:
[[0.45044065]
 [0.0367652 ]
 [0.13935116]
 [0.18660146]
 [0.13935117]
 [0.04340727]]
Total-order Sobol indices:
[[0.45312026]
 [0.03715027]
 [0.14060553]
 [0.18828108]
 [0.14060554]
 [0.04432778]]


In [17]:
# maximum polynomial degree
P = 9
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)

Polynomial degree: 9
Size of PCE basis: 5005
Size of experimental design: 25025
PCE mean estimate: 0.01699534801636744
PCE variance estimate: 1.8397394582929454e-06
First-order Sobol indices:
[[0.45044031]
 [0.03676511]
 [0.13935094]
 [0.18660223]
 [0.139351  ]
 [0.04340721]]
Total-order Sobol indices:
[[0.45312001]
 [0.03715019]
 [0.14060532]
 [0.18828193]
 [0.14060538]
 [0.04432772]]


In [18]:
# maximum polynomial degree
P = 10
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)

Polynomial degree: 10
Size of PCE basis: 8008
Size of experimental design: 40040
PCE mean estimate: 0.01699534784429547
PCE variance estimate: 1.8397402273543512e-06
First-order Sobol indices:
[[0.4504401 ]
 [0.0367651 ]
 [0.13935092]
 [0.18660254]
 [0.13935093]
 [0.04340719]]
Total-order Sobol indices:
[[0.45311981]
 [0.03715018]
 [0.14060531]
 [0.18828226]
 [0.14060532]
 [0.0443277 ]]


In [19]:
# maximum polynomial degree
P = 11
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)

Polynomial degree: 11
Size of PCE basis: 12376
Size of experimental design: 61880
PCE mean estimate: 0.016995347829508695
PCE variance estimate: 1.8397408491056746e-06
First-order Sobol indices:
[[0.45043994]
 [0.03676509]
 [0.13935092]
 [0.18660275]
 [0.1393509 ]
 [0.04340718]]
Total-order Sobol indices:
[[0.45311966]
 [0.03715017]
 [0.1406053 ]
 [0.18828247]
 [0.14060528]
 [0.0443277 ]]


In [5]:
# maximum polynomial degree
P = 12
print("Polynomial degree:", P)
# construct total-degree polynomial basis
polynomial_basis = TotalDegreeBasis(joint, P)

# check the size of the basis
print('Size of PCE basis:', polynomial_basis.polynomials_number)

# create training data
sample_size = int(polynomial_basis.polynomials_number*5)
print('Size of experimental design:', sample_size)

# realizations of random inputs
x_train = joint.rvs(sample_size)
# corresponding model outputs
yy_train = np.array([Margen(a) for a in x_train])

# fit model
least_squares = LeastSquareRegression()
pce = PolynomialChaosExpansion(polynomial_basis=polynomial_basis, regression_method=least_squares)

pce.fit(x_train, yy_train)

mean_est = pce.get_moments()[0]
var_est = pce.get_moments()[1]
print('PCE mean estimate:', mean_est)
print('PCE variance estimate:', var_est)

pce_sensitivity = PceSensitivity(pce)
pce_sensitivity.run()
sobol_first = pce_sensitivity.first_order_indices
sobol_total = pce_sensitivity.total_order_indices
print('First-order Sobol indices:')
print(sobol_first)
print('Total-order Sobol indices:')
print(sobol_total)


Polynomial degree: 12
Size of PCE basis: 18564
Size of experimental design: 92820
PCE mean estimate: 0.01699534781614715
PCE variance estimate: 1.8397408078545104e-06
First-order Sobol indices:
[[0.45043997]
 [0.0367651 ]
 [0.1393509 ]
 [0.18660274]
 [0.1393509 ]
 [0.04340717]]
Total-order Sobol indices:
[[0.45311968]
 [0.03715018]
 [0.14060528]
 [0.18828246]
 [0.14060528]
 [0.04432769]]
